# frozen_string_literal: true
source "https://rubygems.org"

gem 'grape'
gem 'grape-rabl'
gem 'rack-cors', :require => 'rack/cors'
gem 'puma'
gem 'dotenv'
gem 'activerecord', '~> 5.0.2', require: 'active_record'
gem 'otr-activerecord'
gem 'require_all'
gem 'sqlite3'
gem 'rake'
gem 'pry'
gem 'grape-swagger'
