development:
  adapter: 'sqlite3'
  database: 'db/dev.db'
production:
  adapter: postgresql
  database: <% ENV['DATABASE_NAME']%>
  host: localhost
  password: <% ENV['DATABASE_PASSWORD']%>
test:
  adapter: 'sqlite3'
  database: 'db/test.db'
