# frozen_string_literal: true
source "https://rubygems.org"

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib', require: false
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'rake'
gem 'puma'
gem 'require_all'
gem 'pry'
gem 'rack-flash3'
gem 'rack_csrf'
gem 'sinatra-strong-params', :require => 'sinatra/strong-params'
gem 'sprockets'
gem 'sass'
gem 'sinatra-partial'
gem 'will_paginate'
gem 'will_paginate-foundation'
gem 'recaptcha'
gem 'dotenv'
gem 'bcrypt'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'capybara'
  gem 'poltergeist'
  gem 'guard'
  gem 'guard-rspec'
  gem 'rubocop'
  gem 'database_cleaner'
end
