require_relative 'config/environment.rb'
require 'sinatra/activerecord/rake'
require 'rake/sprocketstask'

task :console do
  Pry.start
end

Rake::SprocketsTask.new do |t|
  t.environment = $sprockets
  t.output      = "./public/assets"
  t.assets      = %w( app.js app.css )
end

# https://github.com/janko-m/sinatra-activerecord
# rake -T

# rake db:create_migration NAME=create_users
# rake db:create_migration NAME=create_add_index_to_users
# rake db:migrate

# rake db:seed
# rake console

# t.timestamps

# rake console
# @user = User.find(4)
# @user.posts

# @post = @user.posts.first
# @post.user

# error flash
# pagination
# patrials
# recaptcha

#assets
# rake assets          # Compile assets
# rake clean_assets    # Clean old assets
# rake clobber_assets  # Remove all assets