require_relative 'config/environment.rb'
require 'sinatra/activerecord/rake'

task :console do
  Pry.start
end

# https://github.com/janko-m/sinatra-activerecord
# rake db:create_migration NAME=create_users
# rake db:migrate

# rake db:seed
# rake console