# frozen_string_literal: true
source "https://rubygems.org"

gem 'sqlite3'
gem 'rake'
gem 'pry'
gem 'activesupport'

group :test do
  gem 'rspec'
  gem 'guard'
  gem 'guard-rspec'
  gem 'rubocop'
end
